modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/butterflymods/painttheworld"

[[mods]]
modId="paint-the-world"
version="${file.jarVersion}"
displayName="Paint the World"
#updateJSONURL="https://[insert]"
displayURL="https://curseforge.com/minecraft/mc-mods/paint-the-world"
logoFile="pack.png"
authors="Butterfly Development Team"
description="A Minecraft mod centred around expanding on the dye system with a vanilla feel, and streamlining it with tons of new unique color options"

[[dependencies.paint-the-world]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.paint-the-world]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
